### ISSUE TITLE
Implement Users SetActive

### ISSUE THREAD

**Issue by BenDenger** [kreait/slack-spring-boot-starter#35]
Reference: https://api.slack.com/methods/users.setActive

Acceptance Criteria:
- [ ] Spring Slack Client is extended with given method
- [ ] Spring Slack Test Client is extended with given method
- [ ] JavaDoc/KDoc is added

**Comment by andakawa** [comment]
> This method is no longer functional and the behavior it controlled is no longer offered. The method will no longer exist beginning May 8, 2018.
